### ISSUE TITLE
Ability to specify timestamp while creating durable timers

### ISSUE THREAD

**Issue by akshaykumars10** [microsoft/durabletask-java#103]
In the java SDK, We can only specify a Delay after which the timer will expire. Can we also start supporting timestamp-based durable timers in the JAVA version?
Ref: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-timers?tabs=java

**Comment by cgillum** [comment]
@akshaykumars10 yes, we can look into this.

**Comment by kanupriya15025** [comment]
@cgillum  @kaibocai When will this be available in the SDK?

**Comment by kaibocai** [comment]
> @cgillum @kaibocai When will this be available in the SDK?

Hi @kanupriya15025 , thanks for reaching out. We are actively working on rolling out a new version SDK that will include this feature. I am sorry that I can not provide an accurrate time for now. But we will keep you update once it's avaliable. Thank you very much.
