### ISSUE TITLE
[Eternal Orchestrator] Timers more than 7days giving error

### ISSUE THREAD

**Issue by kanupriya15025** [microsoft/durabletask-java#114]
I have implemented a scheduler out of an eternal orchestrator. This scheduler evaluates a cron expression and calculates the next execution time based on it. This eternal orchestrator now needs to sleep till this next execution time. 
I was reading the documentation on timers in durable framework, and according to [this](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-timers?tabs=java#timer-limitations) there is no limitation on timers for java, however when I tried it I am getting this error : 
` Microsoft.WindowsAzure.Storage: The argument 'initialVisibilityDelay' is larger than maximum of '7.00:00:00' (Parameter 'initialVisibilityDelay').
`

Can you help me understand if this is a bug or am I doing something wrong. Here the delay I am generating is of 44 days.

**Comment by cgillum** [comment]
This sounds like a bug that needs to be investigated.

**Comment by cgillum** [comment]
@kanupriya15025 in the meantime, you can work around this issue by scheduling a series of shorter timers, like this (which is untested, but hopefully illustrates the idea):

```java
private static Task<Void> createLongTimer(TaskOrchestrationContext ctx, Duration duration) {
    Instant startTime = ctx.getCurrentInstant();
    Instant fireAt = startTime.minus(duration);

    Duration maxInterval = Duration.ofDays(3);
    Duration remainingTime = duration;
    while (remainingTime.compareTo(maxInterval) > 0) {
        ctx.createTimer(maxInterval).await();
        remainingTime = Duration.between(ctx.getCurrentInstant(), fireAt);
    }

    return ctx.createTimer(remainingTime);
}
```

The code above breaks up a large duration into intervals of no longer than 3 days.

/cc @kaibocai @shreyas-gopalakrishna I think we should bake this logic into `createTimer()` implementation.

**Comment by kanupriya15025** [comment]
@cgillum Do you have an idea on when this fix can be made available?

**Comment by cgillum** [comment]
@kanupriya15025 I don’t, unfortunately, since I’m not directly involved in the Java SDK release process, but it’s a simple enough fix that I don’t expect it will take the team too long.

**Comment by kanupriya15025** [comment]
@ChrisRomp Can we create an ADO ticket to track this bug?

**Comment by cgillum** [comment]
@kamperiadis this might be a good one for you to take a look at if you have the bandwidth.

**Comment by ChrisRomp** [comment]
@kanupriya15025 does setting a timer based on timestamp help as a workaround? #103 #106

**Comment by kanupriya15025** [comment]
I still the documentation and sdk still working with just duration.
Can you share the usage or sdk version?

**Comment by kanupriya15025** [comment]
@ChrisRomp just a bump on the issue

**Comment by kanupriya15025** [comment]
@ChrisRomp Looks like that feature isn't available yet. As confirmed on the ticket. Can we look at a way to expedite this?
