### ISSUE TITLE
Bug:  Durable Task language SDK was implemented incorrectly, or that the destination language worker is not sending the function result back to the host

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/durabletask-java#120]
I received this error message when using Durable functions in my Java app: 

```
Durable Task language SDK was implemented incorrectly, or that the destination language worker is not sending the function result back to the host
```

Azure Function Core tools version: **4.0.5030**
Azure Functions Maven plugin version: **1.18.0**
Durable task-java version: **1.0.1**

**Comment by cgillum** [comment]
@kbeaugrand are you still having this issue? Which version of extension bundles are you using (it should be in your host.json file)?

/cc @kaibocai

**Comment by kaibocai** [comment]
@kbeaugrand please share a sample function app that is getting you this error. It seems it's same error as https://github.com/microsoft/durabletask-java/issues/126
