### ISSUE TITLE
Support for function chaining in Java SDK

### ISSUE THREAD

**Issue by kanupriya15025** [microsoft/durabletask-java#121]
According to the document here [https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sequence?tabs=python](url), function chaining doesn't have examples on Java. So is it correct to assume it's not supported yet?

My use case here is to call my app like this : 
http://localhost:7071/api/orchestrators/EternalOrchestrator

There are 2 functions here:
1. HTTP Starter Function
2. Eternal Orchestrator Function

I should be able to route my request directly to Eternal Orchestrator from HTTP Starter. Like this example here : 
https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sequence?tabs=csharp#run-the-sample

**Comment by kanupriya15025** [comment]
Looks like it is supported. 
Just needed to change from "Route" to "route" from C# to Java. 


However, it'll be great if the documentation could be updated :)

**Comment by cgillum** [comment]
FYI @lilyjma
