### ISSUE TITLE
Automatic retry not working with Fan-out Fan-in pattern

### ISSUE THREAD

**Issue by akshaykumars10** [microsoft/durabletask-java#149]
I am trying to add automatic retry in my orchestrator function following this document: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=java#automatic-retry-on-failure

I am using the fan-out fan-in pattern in my orchestrator function. With retry logic, I can see my orchestrator function getting stuck in a running state in case of a failure. Do we need to do anything differently to have retry logic with this pattern?

This is what my orchestrator function looks like:

```
RetryPolicy policy = new RetryPolicy(maxRetry, firstRetryInterval);
TaskOptions options = new TaskOptions(policy);
String taskType = task.getType();
parallelTasks.add(ctx.callActivity(taskType, "input for activity function", options, String.class));
.
.
.
.
List<String> parallelResult = ctx.allOf(parallelTasks).await();
```

I have this config on my local setup:
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667
durabletask.azure.functions version: 1.1.1

Please let me know if more details are required.

**Comment by lilyjma** [comment]
@akshaykumars10 - SDK v1.3.0 is released! you can find it here [Central Repository: com/microsoft/durabletask-azure-functions/1.3.0 (apache.org)](https://repo.maven.apache.org/maven2/com/microsoft/durabletask-azure-functions/1.3.0/)
