### ISSUE TITLE
Custom Durable Entities implementation

### ISSUE THREAD

**Issue by nizos** [microsoft/durabletask-java#194]
Is it possible to create an implementation of Durable Entities in Kotlin (or Java)?

I have added durabletask-protobuf as a submodule to my project and have set up gradle to generate the code from it.

I am hoping to be able to use a grpc client to manage the entities. I saw that localhost:4001 is used in the source code here.

I am able to create a managed channel and a stub but i keep getting an `UNKNOWN error thrown by handler` error every time i try to do anything with it.

I am unsure whether what i am trying to accomplish is possible or not and how i should go about it the correct way.

Any and all help is appreciated! Thanks :)

**Comment by kaibocai** [comment]
I don't think Durable Entities is currently supported in Java (Kotlin). Adding @cgillum for confirm.

**Comment by nizos** [comment]
Yeah, that is what I also understood for the documentation as well.

I wonder if it is possible to implement whatever is needed to get it to work for my use case.

I saw that the C# versions supports Durable Entities and I saw that it uses the protobuf to generate the code to facilitate the communication.

That is where i got the idea: Can i also use the grpc/protobuf to facilitate the mechanisms for managing a custom implementation of a durable entity?

Not sure if it is possible but it would be great if it is so. :)

**Comment by davidmrdavid** [comment]
It may be possible, and that would be interesting, though I'm not the expert in this area - @jviau may be able to provide some pointers. We're not actively working on Durable Entities for Java at the moment (from what I know) so I want to call out that if this is something you're willing to experiment on, we'd be open to have an open source contribution of entities for Java as well.

**Comment by nizos** [comment]
@davidmrdavid thanks for the feedback! This is definitely something that i would like to experiment with and contribute to. 🙂

**Comment by davidmrdavid** [comment]
That would be cool, though it may also be a lot, so no pressure, it may be more practical for you to just contribute the bits you need for your usecase. In any case, I'll let @jviau or @sebastianburckhardt possibly list a few code pointers regarding entities and protobuf, as I'm not the expert there.

**Comment by nizos** [comment]
Can I get a few pointers on the direction to take? :)

**Comment by cgillum** [comment]
@nizos can you share a bit more about some of the design objectives?

If you're willing to use the existing orchestration primitives in a customer Durable Entities implementation, I would start by creating a simple abstraction on top of orchestrations. It could be something like this (apologies if this doesn't compile):

```java
@FunctionName("DurableEntityEmulator")
public void durableEntityEmulator(
        @DurableOrchestrationTrigger(name = "ctx") TaskOrchestrationContext ctx) {
    // "state" is the state of the entity
    Object state = ctx.getInput(Object.class);
    
    // entity operations are modeled as external events
    string nextOperation = ctx.waitForExternalEvent("Operation", String.class).await();
    switch (nextOperation) {
        case "Operation1":
            // ... implementation, maybe call an activity and/or modify state
            break;
        case "Operation2":
            // ... implementation, maybe call an activity and/or modify state
            break;
        default:
            // ... special case
            break;
    }

    // make the entity state available for clients to query
    ctx.setCustomStatus(state);

    // start again from the beginning, making the updated state available to the next iteration
    ctx.continueAsNew(state);
}
```

This is actually a big part of how Durable Entities are implemented in other languages today, though with a few additional optimizations.

**Comment by nizos** [comment]
Hi @cgillum!

That was incredibly insightful and helpful! I tested it with a human approval workflow and it worked. I will try the other examples here next:
https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=function-based%2Cin-process%2Cpython-v2&pivots=csharp

The goal is to use this for implementing agentic patterns. Generally speaking, what are some of the optimizations that are done in the other languages?

Thanks again for the help!!

**Comment by cgillum** [comment]
> Generally speaking, what are some of the optimizations that are done in the other languages?

Most of the optimizations are around things like batching. For example, batching multiple concurrent operations into a single function call, which is helpful when there is a high amount of load on a single entity.

Glad to hear this has been helpful! I'll go ahead and close this issue for now, but feel free to get back in touch if you have more questions.
