### ISSUE TITLE
Build and publish pipeline for Maven packages

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-java#27]
Work needs to be done to publish packages to the maven central repository: https://mvnrepository.com/. This includes both the annotations package (currently named `com.microsoft.durabletask.azurefunctions`) and the core SDK package (`com.microsoft.durabletask`)

**Comment by shreyas-gopalakrishna** [comment]
Documenting the steps to follow to release the durabletask client and durabletask annotations packages.

### Build the project and install to local maven repository
Update the package versions in the build.gradle files for both the packages
    - [durabletask-java client](https://github.com/microsoft/durabletask-java/blob/main/client/build.gradle#L10)
    - [durabletask-java annotations](https://github.com/microsoft/durabletask-java/blob/main/azurefunctions/build.gradle)

Configure local system to use JDK 8. Verify using the below command before proceeding
    - `java -version`

Build and install the durable task java client to local maven repository using IntelliJ or the below commands 
    - `gradle client:build`
    - `gradle client:publishToMavenLocal`

Build and install the durable task java annotations to local maven repository using IntelliJ or the below commands 
    - `gradle azurefunctions:build`
    - `gradle azurefunctions:publishToMavenLocal`

The updated jars can be located at the local maven repository in the below path.
    - `C:\Users\<user>\.m2\repository\com\microsoft\durabletask-client\<version>`
    - `C:\Users\<user>\.m2\repository\com\microsoft\durabletask-azure-functions<version>`


### Publish packages to maven
The [Partner Release Pipeline](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/1/Partner-Release-Pipeline) will be used to publish packages into sonatype and maven.

Upload the files from your local maven repository to the [Azure drops container](https://ms.portal.azure.com/#blade/Microsoft_Azure_Storage/ContainerMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fa18897a6-7e44-457d-9260-f2854c0aca42%2FresourceGroups%2FAzureSDKEng%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fazuresdkpartnerdrops/path/drops/etag/%220x8D680AE5A72EEFF%22) 
    - Create a new folder for your package (if a new package) and a version sub folder.
    - Container locations `/azure-functions/java/durabletask-azure-functions/<version>` and `/azure-functions/java/durabletask-client/<version>`
    - Upload the files from your local maven repository to the specific container. Generally, this included 4 files, a pom file, javadoc jar, sources jar and the actual package jar.   
 
Run the [Java Partner Release Pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1809&_a=summary) to publish to sonatype and maven. 
	1. Click Run pipeline
	2. Update the Container relative blob path to point to the respective package in the drops container. Example: `azure-functions/java/durabletask-client/1.0.0-beta.1`
	3. Hit Run
	4. Once the pipeline completes, the jars are published to maven. If the jar is a Snapshot jar, it is only published to sonatype.
