### ISSUE TITLE
Suspend and Resume client APIs

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-java#96]
Here is the feature documentation: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#suspend-and-resume-instances-preview

Here are the equivalent APIs for the .NET in-proc (WebJobs) model:

* https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.suspendasync?view=azure-dotnet#microsoft-azure-webjobs-extensions-durabletask-idurableorchestrationclient-suspendasync(system-string-system-string)
* https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.resumeasync?view=azure-dotnet#microsoft-azure-webjobs-extensions-durabletask-idurableorchestrationclient-resumeasync(system-string-system-string)

**Comment by akshaykumars10** [comment]
Hi @cgillum 
What should be the ETA for this feature in the java SDK?

**Comment by cgillum** [comment]
Adding @kaibocai for visibility.

**Comment by cgillum** [comment]
Here's a PR which shows how we added these APIs in the .NET Isolated SDK: https://github.com/microsoft/durabletask-dotnet/pull/97.

One additional thing we'll need in the case of Java is to also add a suspend/resume implementation to `TaskOrchestrationExecutor.java`, specifically, the `processEvent` method. The basic steps are outlined in this PR: https://github.com/Azure/durabletask/pull/764. You'll want to focus mostly on the changes to `TaskOrchestrationExecutor.cs` (same class name as in Java) but also try to implement a similar integration test for validation.

**Comment by kaibocai** [comment]
> Here's a PR which shows how we added these APIs in the .NET Isolated SDK: [microsoft/durabletask-dotnet#97](https://github.com/microsoft/durabletask-dotnet/pull/97).
> 
> One additional thing we'll need in the case of Java is to also add a suspend/resume implementation to `TaskOrchestrationExecutor.java`, specifically, the `processEvent` method. The basic steps are outlined in this PR: [Azure/durabletask#764](https://github.com/Azure/durabletask/pull/764). You'll want to focus mostly on the changes to `TaskOrchestrationExecutor.cs` (same class name as in Java) but also try to implement a similar integration test for validation.

Thanks @cgillum , I believe I will also add missing logics in https://github.com/microsoft/durabletask-sidecar right.

**Comment by cgillum** [comment]
No, we don’t use the sidecar project anymore for Functions. There’s no need to change anything there.

**Comment by kaibocai** [comment]
Hi @cgillum , so currently all java sdk integration tests are based on durable side car just similar as .NET sdk (seems .NET sdk also skip the test because of missing logics in sidecar https://github.com/microsoft/durabletask-dotnet/pull/97), if we don't use sidecar for the integration tests, are you expecting we spawn up function runtime (just as what we are doing here https://github.com/microsoft/durabletask-java/tree/main/samples-azure-functions) for the testing? Thanks.

**Comment by cgillum** [comment]
Oh, interesting. I didn’t realize that any changes to the sidecar were necessary. Maybe it needs to understood the new `Suspended` enum value? If that’s the case, I recommend we try to update the sidecar to support this because that will make testing easier. My hope is that it’s very little work.

**Comment by cgillum** [comment]
Actually, I just realized that I have local changes on my machine to support suspend/resume. I will create a PR for updating the sidecar.

**Comment by cgillum** [comment]
Here's the PR for suspend/resume support in the sidecar. I don't have a way to test it yet, unfortunately, so I recommend you clone this PR locally and run it locally (F5 in visual studio, debugging the `Microsoft.DurableTask.Sidecar.App` project should be good enough).

https://github.com/microsoft/durabletask-sidecar/pull/18
